import math
import warnings

import torch


def starter_trunc_normal_for_linear_(
    tensor: torch.Tensor,
    in_features: int,
    out_features: int,
    *,
    generator: torch.Generator | None = None,
) -> torch.Tensor:
    """
    Fills the input `tensor` with values drawn from a truncated normal distribution:

    .. math::
        𝒩︀(𝜇 = 0, 𝜎² = 2 / (𝑑_{in}+𝑑_{out}) ) truncated at [-3𝜎, 3𝜎]

    Intended for linear weights.

    Args:
        tensor (torch.Tensor): The tensor to be filled.
        in_features (int): The number of input features.
        out_features (int): The number of output features.
        generator (torch.Generator): an RNG to sample from (default: None)

    Returns:
        torch.Tensor: The filled tensor.
    """
    if 0 in tensor.shape:
        warnings.warn("Initializing zero-element tensors is a no-op", stacklevel=2)
        return tensor
    std: float = (2.0 / (in_features + out_features)) ** 0.5
    _no_grad_trunc_normal_(tensor, 0.0, std, -3 * std, 3 * std, generator)
    return tensor


def starter_trunc_normal_for_embedding_(
    tensor: torch.Tensor,
    *,
    generator: torch.Generator | None = None,
) -> torch.Tensor:
    """
    Fills the input `tensor` with values drawn from a truncated normal distribution:

    .. math::
        𝒩︀(𝜇 = 0, 𝜎² = 1 ) truncated at [-3, 3]

    Intended for embedding.

    Args:
        tensor (torch.Tensor): The tensor to be filled.
        generator (torch.Generator): an RNG to sample from (default: None)

    Returns:
        torch.Tensor: The filled tensor.
    """
    if 0 in tensor.shape:
        warnings.warn("Initializing zero-element tensors is a no-op", stacklevel=2)
        return tensor
    _no_grad_trunc_normal_(tensor, 0.0, 1.0, -3.0, 3.0, generator)
    return tensor


# no_grad utils vendored from :module:`torch.nn.init`


def _no_grad_uniform_(
    tensor: torch.Tensor, a: float, b: float, generator: torch.Generator | None = None
) -> torch.Tensor:
    with torch.no_grad():
        return tensor.uniform_(a, b, generator=generator)


def _no_grad_normal_(
    tensor: torch.Tensor,
    mean: float,
    std: float,
    generator: torch.Generator | None = None,
) -> torch.Tensor:
    with torch.no_grad():
        return tensor.normal_(mean, std, generator=generator)


def _no_grad_trunc_normal_(
    tensor: torch.Tensor,
    mean: float,
    std: float,
    a: float,
    b: float,
    generator: torch.Generator | None = None,
) -> torch.Tensor:
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x: float) -> float:
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l: float = norm_cdf((a - mean) / std)  # noqa: E741
        u: float = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1, generator=generator)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor
